routes/admin.php
<?php

use Illuminate\Support\Facades\Route;


Auth::routes();


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'App\Http\Controllers\Admin', 'middleware' => 'auth'], function(){
    Route::get('/', 'DashboardController@index')->name('welcome');
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    // route setup learning paths
    Route::resource('lpaths', LearningPathController::class);
    Route::resource('courses', CoursesController::class);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/logout', [App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('logout');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


require __DIR__.'/admin.php';

resources/views/_admin/_paths/create.blade.php
@extends('layouts.admin.app')
@section('pages', 'Created Learning Paths')
@push('links')

@endpush
@section('content')
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Add Learning Paths</h3>
    </div>
    <div class="card-body">
        <form method="POST" action="{{route('admin.lpaths.store')}}" enctype="multipart/form-data"> 
            @csrf
            <div class="form-group">
                <label for="title">Paths Name</label>
                <input type="text" id="title" class="form-control @error('title') is-invalid @enderror" name="title" autofocus>

                @error('title')
                    <div class="alert" style="color: red;font-size:13px;"><i>{{ $message }}</i></div>
                @enderror

            </div>
            <div class="form-group">
                <label for="description">Paths Description</label>
                <textarea id="description" class="form-control @error('description') is-invalid @enderror" name="description" rows="4"></textarea>
            
                @error('description')
                    <div class="alert" style="color: red;font-size:13px;"><i>{{ $message }}</i></div>
                @enderror

            </div>
            <div class="form-group">
                <!-- <label for="customFile">Custom File</label> -->

                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="cover" onchange="previewFile(this)" name="cover">
                    <label class="custom-file-label" for="cover">Choose file</label>
                    <img id="viewCover" src="" alt="" style="max-width: 130px;margin-top: 20px;max-height: 130px;" />
                </div>

                @error('cover')
                    <div class="alert" style="color: red;font-size:13px;"><i>{{ $message }}</i></div>
                @enderror
            </div>
            {{-- <div class="form-group">
                <label for="inputStatus">Status</label>
                <select class="form-control custom-select">
                    <option selected="" disabled="">Select one</option>
                    <option>On Hold</option>
                    <option>Canceled</option>
                    <option>Success</option>
                </select>
            </div> --}}
            
            <!-- /.card-body -->
            <div class="row">
                <div class="col-md-6 my-2">
                    <a href="#" class="btn btn-secondary">Cancel</a>
                    <input type="submit" value="Add new" class="btn btn-info">
                </div>
            </div>
        </form>
    </div>
</div>
@endsection
@push('scripts')

{{-- use previewFile Photo Upload function  --}}
<script type="text/javascript">

document.querySelector('.custom-file-input').addEventListener('change',function(e){
    var fileName = document.getElementById("cover").files[0].name;
    var nextSibling = e.target.nextElementSibling
    nextSibling.innerText = fileName
});

</script>
@endpush

resources/views/_admin/_paths/edit.blade.php
@extends('layouts.admin.app')
@section('pages', 'Edited Learning Paths')
@push('links')

@endpush
@section('content')
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Edit Learning Paths</h3>
    </div>
    <div class="card-body">
        <form method="POST" action="{{route('admin.lpaths.update', $paths->slug)}}" enctype="multipart/form-data"> 
            @csrf
            @method('PUT')
            <div class="form-group">
                <label for="title">Paths Name</label>
                <input type="text" id="title" class="form-control @error('title') is-invalid @enderror" name="title" autofocus value="{{$paths->title}}">

                @error('title')
                    <div class="alert" style="color: red;font-size:13px;"><i>{{ $message }}</i></div>
                @enderror

            </div>
            <div class="form-group">
                <label for="description">Paths Description</label>
                <textarea id="description" class="form-control @error('description') is-invalid @enderror" name="description" rows="4">{{$paths->description}}</textarea>
            
                @error('description')
                    <div class="alert" style="color: red;font-size:13px;"><i>{{ $message }}</i></div>
                @enderror

            </div>


            <div class="form-group">
                <!-- <label for="customFile">Custom File</label> -->

                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="cover" onchange="previewFile(this)" name="cover">
                    <label class="custom-file-label" for="cover">Choose file...</label>
                    <img id="viewCover" src="{{asset('storage/paths_cover/')}}/{{$paths->cover}}" alt="" style="max-width: 130px;margin-top: 20px;max-height: 130px;" /> <br>
                </div>

                @error('cover')
                    <div class="alert" style="color: red;font-size:13px;"><i>{{ $message }}</i></div>
                @enderror
            </div>
            <!-- /.card-body -->
            <div class="row">
                <div class="col-md-6 my-5">
                    <a href="#" class="btn btn-secondary">Cancel</a>
                    <input type="submit" value="Edit now" class="btn btn-info">
                </div>
            </div>
        </form>
    </div>
</div>
@endsection
@push('scripts')
{{-- use previewFile Photo Upload function  --}}
<script type="text/javascript">

function previewFile(input){
    var file=$("input[type=file]").get(0).files[0];

    if(file)
    {
        var reader = new FileReader();
        reader.onload = function(){
            $('#previewImg').attr("src", reader.result);
        }
        reader.readAsDataURL(file);
    }
};
    
</script>
@endpush

resources/views/_admin/_paths/index.blade.php
@extends('layouts.admin.app')
@section('pages', 'Learning Paths')
@push('links')
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.7/css/responsive.bootstrap.min.css">
@endpush
@section('content')
<div class="card">
    <div class="card-header">
    <h3 class="card-title">Listing Learning Paths {{$paths->count()}}</h3>
    <a href="{{route('admin.lpaths.create')}}" class="card-title float-right"><i class="fas fa-plus" style="color: green"></i></a>
    </div>
    <div class="card-body">
        <div id="example1_wrapper" class="dataTables_wrapper dt-bootstrap4">
            <table id="example" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>Created</th>
                        <th>Name</th>
                        <th>Cover</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if (($paths->count()) > 0)
                    @foreach ($paths as $path)
                            <tr>
                                <td>{{ $path->created_at->format('D d/m/Y') }}</td>
                                <td>{{ $path->title }}</td>
                                <td class="text-center py-0 align-middle"><img src="{{ asset('storage/paths_cover/'.$path->cover) }}" alt="{{ $path->title }}" style="max-width: 50px;margin-top: 2px;"></td>
                                <td>{{ Str::limit($path->description, 50) }}</td>
                                <td class="text-center py-0 align-middle">
                                    <div class="btn-group btn-group-sm">
                                        <a class="btn btn-info" data-toggle="modal" id="mediumButton" data-target="#modalView{{ $path->id }}"><i class="fas fa-eye" style="color: azure"></i></a>

                                        <a href="{{route('admin.lpaths.edit', $path->slug)}}" class="btn btn-success"><i class="fas fa-edit"></i></a>

                                        <a class="btn btn-danger" data-toggle="modal" id="mediumButton" data-target="#modalDelete{{ $path->slug }}"><i class="fas fa-trash" style="color: azure"></i></a>
                                    </div>
                                </td>
                            </tr>
                    @endforeach
                @else
            
                    <td colspan="6" class="text-center" style="color: #6777ef;">                           
                        <b>Path not found. <a href="{{route('admin.lpaths.create')}}" style="font-weight: bold;">Create here!</a></b>
                    </td>
                    
                @endif
                </tbody>
                <tfoot>
                    <tr>
                        <th>Created</th>
                        <th>Name</th>
                        <th>Cover</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

<!-- Modal view-->
@foreach ($paths as $path)    
<div class="modal fade" id="modalView{{ $path->id }}" style="display: none;" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">{{$path->title}}</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">
          <p>{{$path->description}}</p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <a href="{{ route('admin.lpaths.edit', $path->slug) }}" class="btn btn-info">Edit</a>
        </div>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
@endforeach

<!-- Modal delete-->
@foreach ($paths as $path)    
<div class="modal fade" id="modalDelete{{ $path->slug }}" style="display: none;" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">You are sure delete this paths?</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">
          <p><i>{{$path->title}}</i></p>
        </div>
        <div class="modal-footer">
            <form action="{{route('admin.lpaths.destroy', $path->slug) }}" method="POST">
                @csrf
                @method('delete')
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-danger btn-action">Yes, Delete</button>
            </form>
        </div>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
@endforeach

{{-- attribute tag a --}}
{{-- data-toggle="modal" id="mediumButton" data-target="#mediumModal"
data-attr="{{ route('projects.edit', $project->id) }}" --}}

<!-- Pager -->
{{-- <div class="clearfix mt-4">
    {{$posts->links('vendor.pagination.bootstrap-4')}}
</div> --}}

@endsection
@push('scripts')
<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.7/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.7/js/responsive.bootstrap.min.js"></script>
<script>
    $(function () {
        $("#example").DataTable({
        "responsive": true,
        "autoWidth": false,
        });
    });

    $('#myModal').on('shown.bs.modal', function () {
        $('#myInput').trigger('focus')
    })
</script>
@endpush